# Generated by Django 3.2 on 2022-03-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pss_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
