# Generated by Django 3.2 on 2022-02-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pss_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
