# Generated by Django 3.2 on 2022-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
