# Generated by Django 3.2 on 2022-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_app', '0005_alter_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
